# Generated by Django 4.2.2 on 2023-06-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='perWeek',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество занятий в неделю'),
        ),
    ]
