# Generated by Django 4.2.2 on 2023-06-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0002_alter_student_perweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='otherInformation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='student',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена за занятие'),
        ),
    ]
