# Generated by Django 4.2.2 on 2023-07-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0004_lesson_student_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='solvedTask',
            field=models.CharField(blank=True, max_length=27, verbose_name='Решенные задачи'),
        ),
    ]
