# Generated by Django 4.2.2 on 2023-07-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0005_student_solvedtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.CharField(max_length=20, verbose_name='Название предмета'),
        ),
    ]
