# Generated by Django 4.2.2 on 2023-07-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0006_alter_student_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='otherInformation',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
    ]
