# Generated by Django 4.2.2 on 2023-07-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0007_alter_student_name_alter_student_otherinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='typeOfExam',
            field=models.CharField(max_length=10, verbose_name='Название экзамена'),
        ),
    ]
