# Generated by Django 4.2.2 on 2023-08-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0008_alter_student_typeofexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='overpayment',
            field=models.IntegerField(default=0, verbose_name='Переплата'),
        ),
    ]
