# Generated by Django 4.2.2 on 2023-08-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0009_student_overpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='solvedTask',
            field=models.CharField(default=0, max_length=27, verbose_name='Решенные задачи'),
        ),
    ]
