# Generated by Django 4.2.2 on 2023-08-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0010_alter_student_solvedtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Id')),
                ('sender', models.CharField(max_length=100, verbose_name='Отправитель')),
                ('amount', models.IntegerField(max_length=100, verbose_name='сумма перевода')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата занятия')),
            ],
        ),
    ]
